### ISSUE TITLE
Can I used aFC to calculate the effect size of trans-eQTL

### ISSUE THREAD

**Issue by Bonnie19920126** [secastel/aFC#10]
Hi,
  Thank you for developing this software. I know this tool is applied to the cis-eQTLs, but I want to use it to calculate the allelic Fold Change for trans-eQTLs, do you think it is right? I'm afraid it's not suitable for trans-eQTLs. In addition, my expression value has been transformed to the
quantiles of the standard normal distribution, then should I used the "--log_base" parameter? Thank you very much.

Best wishes

**Comment by secastel** [comment]
Hi there. I don't see any reason that the aFC calculation can't be applied to trans-eQTLs. As for data transformation, you should provide the aFC with expression data that has not been quantile-quantile normalized, as this will produce non biologically meaningful effect size estimates. Ideally one would take read depth normalized count data, add a pseudo count, and then log transform. In this case you would use the options --log_xform 1 --log_base 2 (if you did a log2 transformation). I hope this helps.

**Comment by Bonnie19920126** [comment]
Thank you for your help. I get it.

Best wishes
