### ISSUE TITLE
Estimating aFC with multiple causal variants

### ISSUE THREAD

**Issue by dtaylo95** [secastel/aFC#14]
Not sure if this tool is still supported but I was interested in using it to calculate aFC in some eQTL data I am working with. Some of the genes in this data set are predicted to have multiple causal variants, and I'm wondering if you have any recommendations for how best to calculate the aFC of each causal variant.

In your manuscript, I see that you calculate aFC for GTEx genes with two eQTLs, but I wasn't sure how you actually went about doing that, and I don't see any way to handle this use case in the tool. A naive approach would be just to run the tool as is, which would provide aFC estimates of each variant, but would not account for the additive effects of the variants.

One thought I had is that for each tested eQTL, I could include the other eQTLs for that gene as covariates and regress them out along with the other covariates before estimating aFC. But I'm not sure that would properly handle the discrepancies between cases where the "high expression" alleles are on the same vs. different haplotypes.

Any guidance is greatly appreciated.

**Comment by secastel** [comment]
Hi there - I'm not actively making any updates to this tool. However, Pejman (my co-author and now PI at UW) has extended the method to work exactly for your use case above. You can find the extended method in his lab's github repo: https://github.com/PejLab/aFCn.

I believe the corresponding publication should be coming out shortly, so keep an eye out for that. Hope this helps!

**Comment by dtaylo95** [comment]
Oh, that's perfect! Thank you so much 😄
